name: Tests

on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.100
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Tests
        run: dotnet test --configuration Release --no-build --verbosity normal
